# Generated by Django 2.2 on 2019-04-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('numbering', models.CharField(choices=[('upper-alpha', 'Upper Case Alpha (A, B, C)'), ('lower-alpha', 'Lower Case Alpha (a, b, c'), ('upper-roman', 'Upper Case Roman Numerals (I, II, III)'), ('lower-roman', 'Lower Case Roman Numerals (i, ii, iii)')], default='lower-alpha', max_length=16)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheets.Subject')),
                ('tags', models.ManyToManyField(to='worksheets.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.MultipleChoiceQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='FreeResponseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('answer', models.TextField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='worksheets.Subject')),
                ('tags', models.ManyToManyField(to='worksheets.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
