# Generated by Django 2.2 on 2019-05-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeresponsequestion',
            name='rating',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard'), ('mastery', 'Mastery')], default='beginner', max_length=8),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='rating',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard'), ('mastery', 'Mastery')], default='beginner', max_length=8),
        ),
    ]
